"""Pydantic schemas for API request/response validation."""

from src.schemas.book_schemas import (
    Book,
    BookBase,
    BookCreate,
    BooksListResponse,
    BookWithHighlightCount,
    CoverUploadResponse,
)
from src.schemas.chapter_schemas import Chapter, ChapterBase
from src.schemas.highlight_schemas import (
    BookDetails,
    ChapterWithHighlights,
    Highlight,
    HighlightBase,
    HighlightCreate,
    HighlightDeleteRequest,
    HighlightDeleteResponse,
    HighlightNoteUpdate,
    HighlightNoteUpdateResponse,
    HighlightSearchResponse,
    HighlightSearchResult,
    HighlightUploadRequest,
    HighlightUploadResponse,
)
from src.schemas.highlight_tag_schemas import (
    HighlightTag,
    HighlightTagAssociationRequest,
    HighlightTagBase,
    HighlightTagCreateRequest,
    HighlightTagGroup,
    HighlightTagGroupCreateRequest,
    HighlightTagGroupInBook,
    HighlightTagGroupsResponse,
    HighlightTagInBook,
    HighlightTagsResponse,
    HighlightTagUpdateRequest,
)
from src.schemas.tag_schemas import BookUpdateRequest, Tag

__all__ = [
    "Book",
    "BookBase",
    "BookCreate",
    "BookDetails",
    "BooksListResponse",
    "BookUpdateRequest",
    "BookWithHighlightCount",
    "Chapter",
    "ChapterBase",
    "ChapterWithHighlights",
    "CoverUploadResponse",
    "Highlight",
    "HighlightBase",
    "HighlightCreate",
    "HighlightDeleteRequest",
    "HighlightDeleteResponse",
    "HighlightNoteUpdate",
    "HighlightNoteUpdateResponse",
    "HighlightSearchResponse",
    "HighlightSearchResult",
    "HighlightTag",
    "HighlightTagAssociationRequest",
    "HighlightTagBase",
    "HighlightTagCreateRequest",
    "HighlightTagGroup",
    "HighlightTagGroupCreateRequest",
    "HighlightTagGroupInBook",
    "HighlightTagGroupsResponse",
    "HighlightTagInBook",
    "HighlightTagsResponse",
    "HighlightTagUpdateRequest",
    "HighlightUploadRequest",
    "HighlightUploadResponse",
    "Tag",
]
