"""Pydantic schemas for API request/response validation."""

from src.schemas.book_schemas import (
    Book,
    BookBase,
    BookCreate,
    BooksListResponse,
    BookWithHighlightCount,
    CoverUploadResponse,
    RecentlyViewedBooksResponse,
    TagInBook,
)
from src.schemas.bookmark_schemas import (
    Bookmark,
    BookmarkBase,
    BookmarkCreateRequest,
    BookmarksResponse,
)
from src.schemas.chapter_schemas import Chapter, ChapterBase
from src.schemas.flashcard_api_schemas import (
    FlashcardsWithHighlightsResponse,
    FlashcardWithHighlight,
)
from src.schemas.flashcard_schemas import (
    Flashcard,
    FlashcardBase,
    FlashcardCreate,
    FlashcardCreateRequest,
    FlashcardCreateResponse,
    FlashcardDeleteResponse,
    FlashcardsListResponse,
    FlashcardUpdateRequest,
    FlashcardUpdateResponse,
)
from src.schemas.highlight_schemas import (
    BookDetails,
    BookHighlightSearchResponse,
    ChapterWithHighlights,
    Highlight,
    HighlightBase,
    HighlightCreate,
    HighlightDeleteRequest,
    HighlightDeleteResponse,
    HighlightNoteUpdate,
    HighlightNoteUpdateResponse,
    HighlightResponseBase,
    HighlightSearchResponse,
    HighlightSearchResult,
    HighlightUploadRequest,
    HighlightUploadResponse,
)
from src.schemas.highlight_tag_schemas import (
    HighlightTag,
    HighlightTagAssociationRequest,
    HighlightTagBase,
    HighlightTagCreateRequest,
    HighlightTagGroup,
    HighlightTagGroupCreateRequest,
    HighlightTagGroupInBook,
    HighlightTagGroupsResponse,
    HighlightTagInBook,
    HighlightTagsResponse,
    HighlightTagUpdateRequest,
)
from src.schemas.tag_schemas import BookUpdateRequest, Tag
from src.schemas.user_schemas import UserDetailsResponse, UserRegisterRequest, UserUpdateRequest

__all__ = [
    "Book",
    "BookBase",
    "BookCreate",
    "BookDetails",
    "BookHighlightSearchResponse",
    "BookUpdateRequest",
    "BookWithHighlightCount",
    "Bookmark",
    "BookmarkBase",
    "BookmarkCreateRequest",
    "BookmarksResponse",
    "BooksListResponse",
    "Chapter",
    "ChapterBase",
    "ChapterWithHighlights",
    "CoverUploadResponse",
    "Flashcard",
    "FlashcardBase",
    "FlashcardCreate",
    "FlashcardCreateRequest",
    "FlashcardCreateResponse",
    "FlashcardDeleteResponse",
    "FlashcardUpdateRequest",
    "FlashcardUpdateResponse",
    "FlashcardWithHighlight",
    "FlashcardsListResponse",
    "FlashcardsWithHighlightsResponse",
    "Highlight",
    "HighlightBase",
    "HighlightCreate",
    "HighlightDeleteRequest",
    "HighlightDeleteResponse",
    "HighlightNoteUpdate",
    "HighlightNoteUpdateResponse",
    "HighlightResponseBase",
    "HighlightSearchResponse",
    "HighlightSearchResult",
    "HighlightTag",
    "HighlightTagAssociationRequest",
    "HighlightTagBase",
    "HighlightTagCreateRequest",
    "HighlightTagGroup",
    "HighlightTagGroupCreateRequest",
    "HighlightTagGroupInBook",
    "HighlightTagGroupsResponse",
    "HighlightTagInBook",
    "HighlightTagUpdateRequest",
    "HighlightTagsResponse",
    "HighlightUploadRequest",
    "HighlightUploadResponse",
    "RecentlyViewedBooksResponse",
    "Tag",
    "TagInBook",
    "UserDetailsResponse",
    "UserRegisterRequest",
    "UserUpdateRequest",
]
